version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-data-curation-reference
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: